/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lzybj.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.struts.DispatchActionSupport;

import com.lzybj.service.UsersService;
import com.lzybj.struts.form.UsersForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-28-2013
 * 
 * XDoclet definition:
 * @struts.action path="/users" name="usersForm" parameter="method" scope="request"
 * @struts.action-forward name="succ" path="/succ.jsp"
 * @struts.action-forward name="fail" path="/fail.jsp"
 */
public class UsersAction extends DispatchActionSupport {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UsersForm usersForm = (UsersForm) form;// TODO Auto-generated method stub
		String uname = usersForm.getUname();
		String upwd = usersForm.getUpwd();
		//µ÷ÓÃservice
		WebApplicationContext wac = this.getWebApplicationContext();
		UsersService us = (UsersService)wac.getBean("myservice");
		String logicAddr = "";
		boolean isSucc = us.isLogin(uname, upwd);
		if(isSucc){
			logicAddr = "succ";
			HttpSession session = request.getSession();
			session.setAttribute("uname",uname);
		}else{
			logicAddr = "fail";
		}
		return mapping.findForward(logicAddr);
	}
}