/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lzybj.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.struts.DispatchActionSupport;

import com.lzybj.domain.Customer;
import com.lzybj.service.CustomersService;
import com.lzybj.struts.form.CustomersActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-17-2013
 * 
 * XDoclet definition:
 * @struts.action path="/custaction" name="customersActionForm" parameter="par" scope="request"
 * @struts.action-forward name="succ" path="/res.jsp"
 */
public class CustomerAction extends DispatchActionSupport {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward cx(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CustomersActionForm customersActionForm = (CustomersActionForm) form;// TODO Auto-generated method stub
		String cname = customersActionForm.getCname();
		WebApplicationContext wac = this.getWebApplicationContext();
		CustomersService cs = (CustomersService)wac.getBean("myservice");
		List<Customer> data = cs.findByCName(cname);
		request.setAttribute("data",data);
		return mapping.findForward("succ");
	}
}