/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lzybj.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.DynaActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-17-2013
 * 
 * XDoclet definition:
 * @struts.form name="customersActionForm"
 */
public class CustomersActionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cname property */
	private String cname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		if(cname.equals("")){
			ActionMessage err = new ActionMessage("cx.err.info");
			errors.add("cx_err",err);
		}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		cname = "";
	}

	/** 
	 * Returns the cname.
	 * @return String
	 */
	public String getCname() {
		return cname;
	}

	/** 
	 * Set the cname.
	 * @param cname The cname to set
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}
}