/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lzybj.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-10-2013
 * 
 * XDoclet definition:
 * @struts.form name="regActionForm"
 */
public class RegActionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** uname property */
	private String uname;

	/** upwd property */
	private String upwd;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the uname.
	 * @return String
	 */
	public String getUname() {
		return uname;
	}

	/** 
	 * Set the uname.
	 * @param uname The uname to set
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/** 
	 * Returns the upwd.
	 * @return String
	 */
	public String getUpwd() {
		return upwd;
	}

	/** 
	 * Set the upwd.
	 * @param upwd The upwd to set
	 */
	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}
}