/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lzybj.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.struts.ActionSupport;
import org.springframework.web.struts.DispatchActionSupport;

import com.lzybj.hibernate.domain.Customers;
import com.lzybj.service.CustomersService;
import com.lzybj.struts.form.CXActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-12-2013
 * 
 * XDoclet definition:
 * @struts.action path="/cx" name="cXActionForm" scope="request"
 * @struts.action-forward name="succ" path="/res.jsp"
 */
public class CxAction extends DispatchActionSupport {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward cx(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CXActionForm cXActionForm = (CXActionForm) form;// TODO Auto-generated method stub
		//调用service
		WebApplicationContext wac = this.getWebApplicationContext();
		CustomersService cs = (CustomersService)wac.getBean("myservice");
		List<Customers> data = cs.findByCname(cXActionForm.getCname());
		request.setAttribute("data",data);
		return mapping.findForward("succ");
	}
	
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CXActionForm cXActionForm = (CXActionForm) form;// TODO Auto-generated method stub
		String cname = cXActionForm.getCname();
		String cpwd = cXActionForm.getCpwd();
		//调用service
		WebApplicationContext wac = this.getWebApplicationContext();
		CustomersService cs = (CustomersService)wac.getBean("myservice");
		Customers c = cs.isLogin(cname, cpwd);
		String addr = "";
		if(c != null){
			addr = "oklogin";
			HttpSession session = request.getSession();
			session.setAttribute("c",c);
		}else{
			addr = "fail";
		}
		return mapping.findForward(addr);
	}
}