/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lzybj.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 12-12-2013
 * 
 * XDoclet definition:
 * @struts.form name="cXActionForm"
 */
public class CXActionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cname property */
	private String cname;
	private String cpwd;
	
	

	/*
	 * Generated Methods
	 */

	public String getCpwd() {
		return cpwd;
	}

	public void setCpwd(String cpwd) {
		this.cpwd = cpwd;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		if(cname.equals("")){
			ActionMessage error = new ActionMessage("cx.err.cname");
			errors.add("cname_err",error);
		}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the cname.
	 * @return String
	 */
	public String getCname() {
		return cname;
	}

	/** 
	 * Set the cname.
	 * @param cname The cname to set
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}
}